version: '3.6'

services:
    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
            POSTGRES_LOG_MIN_LEVEL: "fatal"
        command: ["postgres", "-c", "log_min_messages=fatal"]
    bot:
        build: .
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - ./:/rubbergoddess/
        command: python rubbergoddess.py
        depends_on:
            - db

volumes:
    postgres_data:
